# -*- coding: utf-8 -*-
"""Ex_josephus_rodollfo_rivelino.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PJA1nNPrrH6tu23mDVw0B5tKdrFENSZA
"""

## Aluno: Rodolfo Rivelino Franco Cruz
# PECs
# O problema de Josephus descreve a seguinte situação:
# Um grupo de soldados está cercado e não há esperança de vitória,
# porém existe somente um cavalo disponível para escapar e buscar
# por reforços.  Para  determinar qual  soldado  deve escapar para
# encontrar ajuda, eles formam um círculo e sorteiam um número de
# um chapéu. Começando por um soldado sorteado aleatoriamente, uma
# contagem é realizada até o número sorteado. Quando a contagem
# terminar, o soldado em que a contagem parou é removido do círculo,
# um novo número é sorteado e a contagem recomeça no soldado seguinte
# ao que foi eliminado. A cada rodada, portanto, o círculo diminui
# em um, até que somente um soldado reste e seja escolhido para a tarefa.
##

import random as rand

nro_soldados = int(input('Digite a quantidade de soldados: '))

soldados = []
for soldado in range(1, nro_soldados + 1):
    soldados.append(soldado)
    
print(soldados)

# sortear o primeiro soldado
prox_soldado = rand.randrange(1, nro_soldados + 1) # gera um número aleatório inteiro
print('Primeiro soldado: ', prox_soldado)

nro_sorteado = 0 # nenhum soldado selecionado

# loop até que nro_soldados seja = 1
while nro_soldados > 1:
    nro_sorteado = rand.randrange(1, nro_soldados + 1) # gera um nro sorteado
    print('Número sorteado: ', nro_sorteado)
    
    
    # numero do soldado
    # posição
    # [1 (0), 2 (1), 3 (2), 4 (3)]
    # [1 (0), 3 (1), 4(2)]
    
    i_soldado_removido = nro_sorteado + soldados.index(prox_soldado)
    if i_soldado_removido > nro_soldados - 1:
        i_soldado_removido = i_soldado_removido % nro_soldados
    
    print('Soldado removido: ', soldados[i_soldado_removido])
    
    i_prox_soldado = i_soldado_removido + 1
    if i_prox_soldado > nro_soldados - 1:
        i_prox_soldado = i_prox_soldado % nro_soldados
    prox_soldado = soldados[i_prox_soldado]
    
    print('Próximo soldado: ', prox_soldado)
    
    soldados.pop(i_soldado_removido)
    
    nro_soldados = nro_soldados - 1
    
    print(soldados)
    
    print('\n')
    
print('Soldado escolhido: ', soldados[0])